language: node_js
node_js:
  - '0.10'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
notifications:
  slack:
    rooms:
      - about-hiroppy:rzKYJ3zRPzBaak3TeaTmPSH5#travis
      